# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_app', '0003_auto_20161201_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='status',
            field=models.CharField(choices=[('idea', 'idea'), ('bought', 'bought'), ('have', 'have'), ('shipped', 'shipped'), ('wrapped', 'wrapped')], max_length=16),
        ),
    ]
